In [ ]:

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:

from pathlib import Path

PROJECT_DIR = Path("/content/drive/MyDrive/Applied_AI/Team 05")

print("Project folder exists:", PROJECT_DIR.exists())
print("Project path:", PROJECT_DIR)

if PROJECT_DIR.exists():
    print("Folders found:")
    for item in sorted(PROJECT_DIR.iterdir()):
        print("-", item.name)

Project folder exists: False
Project path: /content/drive/MyDrive/Applied_AI/Team 05

In [ ]:

from pathlib import Path

root = Path("/content/drive/MyDrive")

print("Drive connected:", root.exists())
print("Items inside MyDrive:")

for item in root.iterdir():
    print("Folder:" if item.is_dir() else "File:", repr(item.name))

Drive connected: True
Items inside MyDrive:
Folder: 'Colab Notebooks'
Folder: 'Anshinin Folder'
File: 'inbound5828718948187404468.jpg'
File: 'Smack-Ai-chatbot - zip.zip'
File: 'Anshinin Resume.pdf'
File: 'RASA Conversational Chatbot.zip'
File: 'AI integrated plugin Web - Zip file.zip'
File: 'Front_Page_ARJUN_J_S.docx'
File: 'Project_Report_ARJUN_J_S.docx'
File: 'Untitled document.gdoc'
File: 'Blinkit.pbix'
Folder: 'Classroom'
Folder: '963624243009'
Folder: 'Applied_AI'

In [ ]:

from pathlib import Path

applied_ai = Path("/content/drive/MyDrive/Applied_AI")

print("Applied_AI exists:", applied_ai.exists())
print("\nContents of Applied_AI:")

for item in applied_ai.iterdir():
    print("Folder:" if item.is_dir() else "File:", repr(item.name))

Applied_AI exists: True

Contents of Applied_AI:
Folder: 'Team05'

In [ ]:

from pathlib import Path

PROJECT_DIR = Path("/content/drive/MyDrive/Applied_AI/Team 05")

print("Project folder exists:", PROJECT_DIR.exists())

if PROJECT_DIR.exists():
    print("Folders inside Team 05:")
    for item in sorted(PROJECT_DIR.iterdir()):
        print("-", item.name)

Project folder exists: True
Folders inside Team 05:
- artifacts
- datasets
- results

In [ ]:

from pathlib import Path

PROJECT_DIR = Path("/content/drive/MyDrive/Applied_AI/Team 05")

for path in sorted(PROJECT_DIR.rglob("*")):
    print("Folder:" if path.is_dir() else "File:", path.relative_to(PROJECT_DIR))

Folder: artifact
Folder: dataset
Folder: dataset/processed
Folder: dataset/raw
Folder: result

In [ ]:

import torch

print("PyTorch version:", torch.__version__)
print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))
else:
    print("Using CPU for now.")

PyTorch version: 2.11.0+cu130
GPU available: True
GPU name: Tesla T4

In [ ]:

from pathlib import Path
import random
import numpy as np
import torch

# Project location
PROJECT_DIR = Path("/content/drive/MyDrive/Applied_AI/Team 05")

# Reproducibility
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

# Create/check required folders
RAW_DIR = PROJECT_DIR / "dataset" / "raw"
PROCESSED_DIR = PROJECT_DIR / "dataset" / "processed"
ARTIFACTS_DIR = PROJECT_DIR / "artifacts"
RESULTS_DIR = PROJECT_DIR / "results"

for folder in [RAW_DIR, PROCESSED_DIR, ARTIFACTS_DIR, RESULTS_DIR]:
    folder.mkdir(parents=True, exist_ok=True)
    print("Ready:", folder.relative_to(PROJECT_DIR))

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("\nDevice:", DEVICE)
print("Random seed:", SEED)

Ready: dataset/raw
Ready: dataset/processed
Ready: artifacts
Ready: results

Device: cuda
Random seed: 42

In [ ]:

%pip -q install datasets huggingface_hub pyarrow

In [ ]:

import datasets
import huggingface_hub
import pyarrow

print("datasets:", datasets.__version__)
print("huggingface_hub:", huggingface_hub.__version__)
print("pyarrow:", pyarrow.__version__)
print("Installation verified successfully!")

datasets: 4.8.5
huggingface_hub: 1.33.0
pyarrow: 23.0.1
Installation verified successfully!

In [ ]:

from datasets import get_dataset_config_names, get_dataset_split_names

DATASET_NAME = "SetFit/toxic_conversations"

print("Dataset:", DATASET_NAME)

try:
    configs = get_dataset_config_names(DATASET_NAME)
    print("\nAvailable configurations:")
    print(configs)

    for config in configs:
        print(f"\nSplits for configuration: {config}")
        print(get_dataset_split_names(DATASET_NAME, config))
except Exception as e:
    print("\nDataset inspection failed:")
    print(type(e).__name__, str(e))

Dataset: SetFit/toxic_conversations

README.md:   0%|          | 0.00/507 [00:00<?, ?B/s]

Repo card metadata block was not found. Setting CardData to empty.
WARNING:huggingface_hub.repocard:Repo card metadata block was not found. Setting CardData to empty.
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Available configurations:
['default']

Splits for configuration: default

Repo card metadata block was not found. Setting CardData to empty.
WARNING:huggingface_hub.repocard:Repo card metadata block was not found. Setting CardData to empty.

['train', 'test']

In [ ]:

from datasets import load_dataset
from collections import Counter

DATASET_NAME = "SetFit/toxic_conversations"

print("Loading official training split...")
train_source = load_dataset(DATASET_NAME, split="train")

print("Loading official test split...")
test_source = load_dataset(DATASET_NAME, split="test")

print("\n--- TRAINING SPLIT ---")
print("Rows:", len(train_source))
print("Columns:", train_source.column_names)
print("Features:", train_source.features)

print("\n--- TEST SPLIT ---")
print("Rows:", len(test_source))
print("Columns:", test_source.column_names)
print("Features:", test_source.features)

print("\n--- TRAINING EXAMPLES ---")
for row in train_source.select(range(min(3, len(train_source)))):
    print(row)

print("\n--- LABEL COUNTS ---")
for split_name, data in [
    ("train", train_source),
    ("test", test_source)
]:
    for column in data.column_names:
        if column.lower() in {"label", "labels", "target", "toxicity", "is_toxic"}:
            print(f"{split_name} - {column}:")
            print(Counter(data[column]))

Loading official training split...

Repo card metadata block was not found. Setting CardData to empty.
WARNING:huggingface_hub.repocard:Repo card metadata block was not found. Setting CardData to empty.

train.jsonl: reconstructing file:   0%|          |  0.00B /  617MB

train.jsonl: downloading bytes:           |  0.00B

test.jsonl: reconstructing file:   0%|          |  0.00B / 17.5MB

test.jsonl: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/1754874 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/50000 [00:00<?, ? examples/s]

Loading official test split...

Repo card metadata block was not found. Setting CardData to empty.
WARNING:huggingface_hub.repocard:Repo card metadata block was not found. Setting CardData to empty.

--- TRAINING SPLIT ---
Rows: 1754874
Columns: ['text', 'label', 'label_text']
Features: {'text': Value('string'), 'label': Value('int64'), 'label_text': Value('string')}

--- TEST SPLIT ---
Rows: 50000
Columns: ['text', 'label', 'label_text']
Features: {'text': Value('string'), 'label': Value('int64'), 'label_text': Value('string')}

--- TRAINING EXAMPLES ---
{'text': 'theres not enough going on around here for air service none want to waste there time on this town', 'label': 0, 'label_text': 'not toxic'}
{'text': 'How about ZERO', 'label': 0, 'label_text': 'not toxic'}
{'text': 'Her name is still floating?  Might I suggest flushing twice?', 'label': 0, 'label_text': 'not toxic'}

--- LABEL COUNTS ---
train - label:
Counter({0: 1614494, 1: 140380})
test - label:
Counter({0: 46046, 1: 3954})

In [ ]:
from pathlib import Path

PROJECT_DIR = Path("/content/drive/MyDrive/Applied_AI/Team 05")
RAW_DIR = PROJECT_DIR / "dataset" / "raw"
RESULTS_DIR = PROJECT_DIR / "results"

print("RAW DATA FILES")
for file in sorted(RAW_DIR.glob("*")):
    print(
        file.name,
        "-",
        round(file.stat().st_size / (1024**2), 2),
        "MiB"
    )

print("\nSource manifest exists:",
      (RESULTS_DIR / "source_manifest.json").exists())

RAW DATA FILES

Source manifest exists: False

In [ ]:
from datasets import load_dataset
from datetime import datetime, timezone
import json

DATASET_ID = "SetFit/toxic_conversations"
CONFIGURATION = "default"

# Load the official source splits
source = load_dataset(DATASET_ID, CONFIGURATION)

source_details = {}

for split_name, split_data in source.items():
    part = split_data.to_pandas().copy()
    part["source_split"] = split_name

    raw_path = RAW_DIR / f"source_{split_name}.parquet"
    part.to_parquet(raw_path, index=False)

    source_details[split_name] = {
        "filename": raw_path.name,
        "rows": len(part),
        "columns": part.columns.tolist(),
        "size_bytes": raw_path.stat().st_size,
    }

    print(f"Saved: {raw_path.name}")
    print("Rows:", len(part))

manifest = {
    "dataset": DATASET_ID,
    "source_url": f"https://huggingface.co/datasets/{DATASET_ID}",
    "publisher": "Hugging Face dataset repository",
    "configuration": CONFIGURATION,
    "published_splits": list(source.keys()),
    "download_date_utc": datetime.now(timezone.utc).isoformat(),
    "license": "Not yet verified",
    "backup_used": False,
    "text_column": "text",
    "numeric_label_column": "label",
    "human_readable_label_column": "label_text",
    "files": source_details,
}

manifest_path = RESULTS_DIR / "source_manifest.json"
manifest_path.write_text(
    json.dumps(manifest, indent=2),
    encoding="utf-8"
)

print("\nManifest saved:", manifest_path)
print("Raw source backup completed.")

Repo card metadata block was not found. Setting CardData to empty.
WARNING:huggingface_hub.repocard:Repo card metadata block was not found. Setting CardData to empty.

Saved: source_train.parquet
Rows: 1754874
Saved: source_test.parquet
Rows: 50000

Manifest saved: /content/drive/MyDrive/Applied_AI/Team 05/results/source_manifest.json
Raw source backup completed.

In [ ]:
import pandas as pd
import json

train_path = RAW_DIR / "source_train.parquet"
test_path = RAW_DIR / "source_test.parquet"

train_df = pd.read_parquet(train_path)
test_df = pd.read_parquet(test_path)

for split_name, df in [
    ("TRAIN", train_df),
    ("TEST", test_df)
]:
    print(f"\n{'=' * 40}")
    print(f"{split_name} DATASET")
    print("=" * 40)

    print("Shape:", df.shape)
    print("Columns:", df.columns.tolist())
    print("\nData types:")
    print(df.dtypes)

    print("\nFirst 5 rows:")
    display(df.head())

    print("\nMissing values:")
    print(df[["text", "label", "label_text"]].isna().sum())

    print("\nExact duplicate rows:", df.duplicated().sum())
    print("Duplicate text values:", df["text"].duplicated().sum())

    print("\nLabel counts:")
    print(df["label_text"].value_counts(dropna=False))

    text_lengths = df["text"].fillna("").astype(str).str.len()
    print("\nText length statistics:")
    print(text_lengths.describe(percentiles=[0.25, 0.50, 0.75, 0.95]))

print("\nInspection complete. Original files remain unchanged.")

========================================
TRAIN DATASET
========================================
Shape: (1754874, 4)
Columns: ['text', 'label', 'label_text', 'source_split']

Data types:
text            object
label            int64
label_text      object
source_split    object
dtype: object

First 5 rows:

,text,label,label_text,source_split
0,theres not enough going on around here for air...,0,not toxic,train
1,How about ZERO,0,not toxic,train
2,Her name is still floating? Might I suggest f...,0,not toxic,train
3,Stop by So Cold at MFNW/Project Pabst! It'll m...,0,not toxic,train
4,"Nobody awake on the bridge, no lookouts ,,no r...",0,not toxic,train

Missing values:
text          0
label         0
label_text    0
dtype: int64

Exact duplicate rows: 22512
Duplicate text values: 23091

Label counts:
label_text
not toxic    1614494
toxic         140380
Name: count, dtype: int64

Text length statistics:
count    1.754874e+06
mean     2.972533e+02
std      2.692077e+02
min      1.000000e+00
25%      9.400000e+01
50%      2.020000e+02
75%      4.140000e+02
95%      9.530000e+02
max      1.906000e+03
Name: text, dtype: float64

========================================
TEST DATASET
========================================
Shape: (50000, 4)
Columns: ['text', 'label', 'label_text', 'source_split']

Data types:
text            object
label            int64
label_text      object
source_split    object
dtype: object

First 5 rows:

,text,label,label_text,source_split
0,Bingo: Everything is always about growth int ...,0,not toxic,test
1,stop making excuse for your infantile and stup...,1,toxic,test
2,Here is something else you can do: Get the Gov...,0,not toxic,test
3,I was asked by a Canada Custom Officer to remo...,0,not toxic,test
4,The debate is over. 97% of geneticists agree t...,0,not toxic,test

Missing values:
text          0
label         0
label_text    0
dtype: int64

Exact duplicate rows: 103
Duplicate text values: 104

Label counts:
label_text
not toxic    46046
toxic         3954
Name: count, dtype: int64

Text length statistics:
count    50000.000000
mean       296.569520
std        268.810527
min          1.000000
25%         93.000000
50%        202.000000
75%        412.000000
95%        948.000000
max       1000.000000
Name: text, dtype: float64

Inspection complete. Original files remain unchanged.

In [ ]:
for split_name, df in [("TRAIN", train_df), ("TEST", test_df)]:
    label_counts_per_text = df.groupby("text")["label"].nunique()
    conflicts = label_counts_per_text[label_counts_per_text > 1]

    print(f"\n{split_name} LABEL CONSISTENCY")
    print("Unique comment texts:", df["text"].nunique())
    print("Comments with conflicting labels:", len(conflicts))

    if len(conflicts) > 0:
        display(
            df[df["text"].isin(conflicts.index)]
            [["text", "label", "label_text"]]
            .drop_duplicates()
            .head(10)
        )

TRAIN LABEL CONSISTENCY
Unique comment texts: 1731783
Comments with conflicting labels: 579

                                                   text  label label_text
11    YES CANADA IS BACK!!\n\nThe national embarrass...      0  not toxic
1522  I agree.  Trump is most definitely a worthless...      0  not toxic
1814                                           Rubbish.      1      toxic
4694  The domestic terrorists at the company called ...      0  not toxic
5453  It’s easy to get caught up in the deeply flawe...      0  not toxic
5887  One million Canadians MUST walk on Parliament ...      0  not toxic
6571  Shakespeare’s Hamlet, who suffered from melanc...      0  not toxic
8838  Stop the closed door meetings between state an...      0  not toxic
8935  You feel the Republican party holds itself to ...      1      toxic
9471  you have all the character and credibility of ...      1      toxic

TEST LABEL CONSISTENCY
Unique comment texts: 49896
Comments with conflicting labels: 1

                                                    text  label label_text
5382   Tabatha really knows how to stick it to the de...      0  not toxic
29306  Tabatha really knows how to stick it to the de...      1      toxic

In [ ]:
import pandas as pd

def normalize_text(series):
    return (
        series.fillna("")
        .astype(str)
        .str.lower()
        .str.replace(r"\s+", " ", regex=True)
        .str.strip()
    )

train_texts = set(normalize_text(train_df["text"]))
test_texts = set(normalize_text(test_df["text"]))

overlap = train_texts.intersection(test_texts)

print("Unique normalized training comments:", len(train_texts))
print("Unique normalized test comments:", len(test_texts))
print("Comments appearing in both splits:", len(overlap))
print("Test comments overlapping training (%):",
      round(len(overlap) / len(test_texts) * 100, 3))

Unique normalized training comments: 1727656
Unique normalized test comments: 49876
Comments appearing in both splits: 1014
Test comments overlapping training (%): 2.033

In [ ]:
# Work on a copy; preserve train_df and test_df.
train_work = train_df.copy()

train_work["normalized_text"] = normalize_text(train_work["text"])
test_normalized = normalize_text(test_df["text"])

# Remove blank comments.
train_work = train_work[train_work["normalized_text"] != ""].copy()

# Find normalized comments that have conflicting labels.
label_counts = train_work.groupby("normalized_text")["label"].nunique()
conflicting_texts = set(label_counts[label_counts > 1].index)

before_conflicts = len(train_work)
train_work = train_work[
    ~train_work["normalized_text"].isin(conflicting_texts)
].copy()

print("Training rows removed for conflicting labels:",
      before_conflicts - len(train_work))

# Remove comments that overlap with the official test set.
test_text_set = set(test_normalized)
before_overlap = len(train_work)

train_work = train_work[
    ~train_work["normalized_text"].isin(test_text_set)
].copy()

print("Training rows removed for test overlap:",
      before_overlap - len(train_work))

# Keep one example per normalized comment.
before_dedup = len(train_work)
train_work = train_work.drop_duplicates(
    subset="normalized_text",
    keep="first"
).copy()

print("Duplicate training rows removed:", before_dedup - len(train_work))

print("\nRemaining training candidate rows:", len(train_work))
print("\nLabel counts:")
print(train_work["label_text"].value_counts())

print("\nNumeric label counts:")
print(train_work["label"].value_counts().sort_index())

Training rows removed for conflicting labels: 2626
Training rows removed for test overlap: 7051
Duplicate training rows removed: 19299

Remaining training candidate rows: 1725898

Label counts:
label_text
not toxic    1588200
toxic         137698
Name: count, dtype: int64

Numeric label counts:
label
0    1588200
1     137698
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
import pandas as pd

SEED = 42

# 1. Split the cleaned data BEFORE balancing the training set.
train_pool, validation_df = train_test_split(
    train_work,
    test_size=0.20,
    random_state=SEED,
    stratify=train_work["label"]
)

# 2. Select an equal number of examples from each class.
balanced_train = pd.concat(
    [
        train_pool[train_pool["label"] == 0].sample(
            n=6000, random_state=SEED
        ),
        train_pool[train_pool["label"] == 1].sample(
            n=6000, random_state=SEED
        ),
    ],
    ignore_index=True
).sample(frac=1, random_state=SEED).reset_index(drop=True)

# 3. Keep only the required dataset columns.
columns = ["text", "label", "label_text", "source_split"]

train_final = balanced_train[columns].copy()
validation_final = validation_df[columns].copy()

# Preserve the official test data without changing its rows or labels.
test_final = test_df[columns].copy()

# 4. Save the prepared datasets to Google Drive.
train_final.to_csv(PROCESSED_DIR / "train.csv", index=False)
validation_final.to_csv(PROCESSED_DIR / "validation.csv", index=False)
test_final.to_csv(PROCESSED_DIR / "test.csv", index=False)

# 5. Report counts and class distributions.
for name, df in [
    ("TRAIN", train_final),
    ("VALIDATION", validation_final),
    ("TEST", test_final),
]:
    print(f"\n{name}: {df.shape}")
    print(df["label_text"].value_counts())
    print("Label counts:", df["label"].value_counts().sort_index().to_dict())

print("\nSaved prepared datasets to:", PROCESSED_DIR)

TRAIN: (12000, 4)
label_text
not toxic    6000
toxic        6000
Name: count, dtype: int64
Label counts: {0: 6000, 1: 6000}

VALIDATION: (345180, 4)
label_text
not toxic    317640
toxic         27540
Name: count, dtype: int64
Label counts: {0: 317640, 1: 27540}

TEST: (50000, 4)
label_text
not toxic    46046
toxic         3954
Name: count, dtype: int64
Label counts: {0: 46046, 1: 3954}

Saved prepared datasets to: /content/drive/MyDrive/Applied_AI/Team 05/dataset/processed

In [ ]:
def normalized_set(df):
    return set(normalize_text(df["text"]))

train_set = normalized_set(train_final)
validation_set = normalized_set(validation_final)
test_set = normalized_set(test_final)

print("Train ∩ Validation:", len(train_set & validation_set))
print("Train ∩ Test:", len(train_set & test_set))
print("Validation ∩ Test:", len(validation_set & test_set))

Train ∩ Validation: 0
Train ∩ Test: 0
Validation ∩ Test: 0

In [ ]:
from collections import Counter
import json
import re

SEED = 42
MAX_VOCAB_SIZE = 20000

PAD_TOKEN = "<PAD>"
UNK_TOKEN = "<UNK>"

def tokenize(text):
    return re.findall(r"\b\w+\b|[^\w\s]", str(text).lower())

# Learn vocabulary from training data only.
word_counts = Counter()

for text in train_final["text"]:
    word_counts.update(tokenize(text))

most_common = word_counts.most_common(MAX_VOCAB_SIZE - 2)

vocabulary = {
    PAD_TOKEN: 0,
    UNK_TOKEN: 1,
}

for word, count in most_common:
    if word not in vocabulary:
        vocabulary[word] = len(vocabulary)

# Save the vocabulary and label mapping.
vocab_path = ARTIFACTS_DIR / "vocabulary.json"
vocab_path.write_text(
    json.dumps(vocabulary, ensure_ascii=False, indent=2),
    encoding="utf-8"
)

labels = {
    "0": "non-toxic",
    "1": "toxic"
}

labels_path = ARTIFACTS_DIR / "labels.json"
labels_path.write_text(
    json.dumps(labels, indent=2),
    encoding="utf-8"
)

print("Vocabulary size:", len(vocabulary))
print("Padding token ID:", vocabulary[PAD_TOKEN])
print("Unknown token ID:", vocabulary[UNK_TOKEN])
print("Saved vocabulary:", vocab_path)
print("Saved labels:", labels_path)
print("\nExample tokenization:", tokenize("You are toxic!"))

Vocabulary size: 20000
Padding token ID: 0
Unknown token ID: 1
Saved vocabulary: /content/drive/MyDrive/Applied_AI/Team 05/artifacts/vocabulary.json
Saved labels: /content/drive/MyDrive/Applied_AI/Team 05/artifacts/labels.json

Example tokenization: ['you', 'are', 'toxic', '!']

In [ ]:
import torch
from torch.utils.data import Dataset, DataLoader

MAX_LENGTH = 128
BATCH_SIZE = 32

class ToxicityDataset(Dataset):
    def __init__(self, dataframe, vocabulary, max_length=128):
        self.texts = dataframe["text"].astype(str).tolist()
        self.labels = dataframe["label"].astype(int).tolist()
        self.vocabulary = vocabulary
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, index):
        tokens = tokenize(self.texts[index])
        token_ids = [
            self.vocabulary.get(token, self.vocabulary["<UNK>"])
            for token in tokens
        ]

        # Truncate long comments and pad short comments.
        token_ids = token_ids[:self.max_length]
        attention_mask = [1] * len(token_ids)

        padding_length = self.max_length - len(token_ids)
        token_ids += [self.vocabulary["<PAD>"]] * padding_length
        attention_mask += [0] * padding_length

        return (
            torch.tensor(token_ids, dtype=torch.long),
            torch.tensor(attention_mask, dtype=torch.long),
            torch.tensor(self.labels[index], dtype=torch.long),
        )

train_dataset = ToxicityDataset(train_final, vocabulary, MAX_LENGTH)
validation_dataset = ToxicityDataset(
    validation_final, vocabulary, MAX_LENGTH
)

train_loader = DataLoader(
    train_dataset, batch_size=BATCH_SIZE, shuffle=True
)
validation_loader = DataLoader(
    validation_dataset, batch_size=BATCH_SIZE, shuffle=False
)

# Inspect one batch before training.
input_ids, attention_mask, labels_batch = next(iter(train_loader))

print("Input IDs shape:", input_ids.shape)
print("Attention mask shape:", attention_mask.shape)
print("Labels shape:", labels_batch.shape)
print("Example labels:", labels_batch[:10].tolist())
print("GPU available:", torch.cuda.is_available())

Input IDs shape: torch.Size([32, 128])
Attention mask shape: torch.Size([32, 128])
Labels shape: torch.Size([32])
Example labels: [0, 0, 1, 0, 1, 1, 1, 0, 0, 1]
GPU available: True

In [7]:
import torch
import torch.nn as nn
import json

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

class ToxicityTransformer(nn.Module):
    def __init__(
        self,
        vocab_size,
        d_model=128,
        nhead=4,
        num_layers=2,
        max_length=128,
        num_classes=2,
        dropout=0.2,
    ):
        super().__init__()

        self.token_embedding = nn.Embedding(
            vocab_size, d_model, padding_idx=0
        )
        self.position_embedding = nn.Embedding(max_length, d_model)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model,
            nhead=nhead,
            dim_feedforward=256,
            dropout=dropout,
            batch_first=True,
        )
        self.encoder = nn.TransformerEncoder(
            encoder_layer, num_layers=num_layers
        )

        self.dropout = nn.Dropout(dropout)
        self.classifier = nn.Linear(d_model, num_classes)

    def forward(self, input_ids, attention_mask):
        batch_size, seq_length = input_ids.shape

        positions = torch.arange(
            seq_length, device=input_ids.device
        ).unsqueeze(0).expand(batch_size, -1)

        x = (
            self.token_embedding(input_ids)
            + self.position_embedding(positions)
        )

        # True marks padding positions that the encoder should ignore.
        padding_mask = attention_mask == 0

        x = self.encoder(x, src_key_padding_mask=padding_mask)

        # Average only real token positions, not padding.
        mask = attention_mask.unsqueeze(-1).float()
        pooled = (x * mask).sum(dim=1) / mask.sum(dim=1).clamp(min=1)

        return self.classifier(self.dropout(pooled))


model = ToxicityTransformer(
    vocab_size=len(vocabulary),
    max_length=MAX_LENGTH,
).to(DEVICE)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-4)

# Test one batch before training.
input_ids, attention_mask, labels_batch = next(iter(train_loader))
input_ids = input_ids.to(DEVICE)
attention_mask = attention_mask.to(DEVICE)
labels_batch = labels_batch.to(DEVICE)

model.train()
optimizer.zero_grad()

logits = model(input_ids, attention_mask)
loss = criterion(logits, labels_batch)
loss.backward()

gradients_finite = all(
    p.grad is None or torch.isfinite(p.grad).all().item()
    for p in model.parameters()
)

print("Device:", DEVICE)
print("Model parameters:", sum(p.numel() for p in model.parameters()))
print("Logits shape:", tuple(logits.shape))
print("Loss:", round(loss.item(), 4))
print("Logits finite:", torch.isfinite(logits).all().item())
print("Gradients finite:", gradients_finite)

assert logits.shape == (BATCH_SIZE, 2)
assert torch.isfinite(logits).all()
assert torch.isfinite(loss)
assert gradients_finite

print("\nTransformer batch test passed!")

NameError: name 'vocabulary' is not defined

In [ ]:

import copy
import json
import pandas as pd
import numpy as np
import torch
from torch.utils.data import DataLoader
from sklearn.metrics import f1_score
from tqdm.auto import tqdm

EPOCHS = 5
PATIENCE = 2
VALIDATION_SAMPLE_SIZE = 20000
SEED = 42

torch.manual_seed(SEED)
np.random.seed(SEED)

# Sample validation rows while preserving the original columns.
validation_sample = (
    validation_final.groupby("label", group_keys=False)
    .apply(
        lambda group: group.sample(
            n=max(
                1,
                round(
                    VALIDATION_SAMPLE_SIZE
                    * len(group)
                    / len(validation_final)
                ),
            ),
            random_state=SEED,
        )
    )
    .reset_index(drop=True)
)

validation_sample = validation_sample[
    ["text", "label", "label_text", "source_split"]
].sample(frac=1, random_state=SEED).reset_index(drop=True)

validation_sample.to_csv(
    RESULTS_DIR / "validation_sample.csv", index=False
)

validation_sample_dataset = ToxicityDataset(
    validation_sample, vocabulary, MAX_LENGTH
)
validation_sample_loader = DataLoader(
    validation_sample_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    pin_memory=torch.cuda.is_available(),
)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    pin_memory=torch.cuda.is_available(),
)

best_f1 = -1.0
best_state = None
epochs_without_improvement = 0
history = []

for epoch in range(1, EPOCHS + 1):
    model.train()
    total_train_loss = 0.0

    for input_ids, attention_mask, labels_batch in tqdm(
        train_loader, desc=f"Epoch {epoch}/{EPOCHS}"
    ):
        input_ids = input_ids.to(DEVICE)
        attention_mask = attention_mask.to(DEVICE)
        labels_batch = labels_batch.to(DEVICE)

        optimizer.zero_grad(set_to_none=True)
        logits = model(input_ids, attention_mask)
        loss = criterion(logits, labels_batch)

        if not torch.isfinite(loss):
            raise ValueError("Non-finite training loss detected.")

        loss.backward()
        torch.nn.utils.clip_grad_norm_(
            model.parameters(), max_norm=1.0
        )
        optimizer.step()
        total_train_loss += loss.item()

    avg_train_loss = total_train_loss / len(train_loader)

    model.eval()
    total_val_loss = 0.0
    val_predictions = []
    val_targets = []

    with torch.no_grad():
        for input_ids, attention_mask, labels_batch in validation_sample_loader:
            input_ids = input_ids.to(DEVICE)
            attention_mask = attention_mask.to(DEVICE)
            labels_batch = labels_batch.to(DEVICE)

            logits = model(input_ids, attention_mask)
            loss = criterion(logits, labels_batch)
            total_val_loss += loss.item()

            val_predictions.extend(logits.argmax(dim=1).cpu().tolist())
            val_targets.extend(labels_batch.cpu().tolist())

    avg_val_loss = total_val_loss / len(validation_sample_loader)
    val_macro_f1 = f1_score(
        val_targets, val_predictions,
        average="macro", zero_division=0
    )

    history.append({
        "epoch": epoch,
        "train_loss": avg_train_loss,
        "validation_loss": avg_val_loss,
        "validation_macro_f1": val_macro_f1,
    })

    print(
        f"Epoch {epoch}: train_loss={avg_train_loss:.4f}, "
        f"validation_loss={avg_val_loss:.4f}, "
        f"validation_macro_f1={val_macro_f1:.4f}"
    )

    if val_macro_f1 > best_f1:
        best_f1 = val_macro_f1
        best_state = copy.deepcopy(model.state_dict())
        epochs_without_improvement = 0

        torch.save(best_state, ARTIFACTS_DIR / "best_model.pt")
        print("Saved new best checkpoint.")
    else:
        epochs_without_improvement += 1
        if epochs_without_improvement >= PATIENCE:
            print("Early stopping triggered.")
            break

if best_state is None:
    raise RuntimeError("No valid model checkpoint was saved.")

model.load_state_dict(best_state)

pd.DataFrame(history).to_csv(
    RESULTS_DIR / "epoch_history.csv", index=False
)

config = {
    "vocab_size": len(vocabulary),
    "d_model": 128,
    "nhead": 4,
    "num_layers": 2,
    "max_length": MAX_LENGTH,
    "num_classes": 2,
    "dropout": 0.2,
    "batch_size": BATCH_SIZE,
    "learning_rate": 2e-4,
    "best_validation_macro_f1": best_f1,
    "epochs_completed": len(history),
    "seed": SEED,
}

(ARTIFACTS_DIR / "model_config.json").write_text(
    json.dumps(config, indent=2), encoding="utf-8"
)

print("\nTraining complete.")
print("Best validation macro F1:", round(best_f1, 4))
print("Best model:", ARTIFACTS_DIR / "best_model.pt")

/tmp/ipykernel_514/2200958175.py:21: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

Epoch 1/5:   0%|          | 0/375 [00:00<?, ?it/s]

/usr/local/lib/python3.13/dist-packages/torch/nn/modules/transformer.py:531: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. We recommend specifying layout=torch.jagged when constructing a nested tensor, as this layout receives active development, has better operator coverage, and works with torch.compile. (Triggered internally at /pytorch/aten/src/ATen/NestedTensorImpl.cpp:178.)
  output = torch._nested_tensor_from_mask(

Epoch 1: train_loss=0.6838, validation_loss=0.6847, validation_macro_f1=0.4520
Saved new best checkpoint.

Epoch 2/5:   0%|          | 0/375 [00:00<?, ?it/s]

Epoch 2: train_loss=0.6348, validation_loss=0.4323, validation_macro_f1=0.5993
Saved new best checkpoint.

Epoch 3/5:   0%|          | 0/375 [00:00<?, ?it/s]

Epoch 3: train_loss=0.5781, validation_loss=0.6115, validation_macro_f1=0.5303

Epoch 4/5:   0%|          | 0/375 [00:00<?, ?it/s]

Epoch 4: train_loss=0.5241, validation_loss=0.6019, validation_macro_f1=0.5396
Early stopping triggered.

Training complete.
Best validation macro F1: 0.5993
Best model: /content/drive/MyDrive/Applied_AI/Team 05/artifacts/best_model.pt

In [ ]:

# STEP 1: Evaluate the best saved model on the untouched test set

import json
import torch
import pandas as pd
import numpy as np
from torch.utils.data import DataLoader
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# Load the best model checkpoint
checkpoint_path = ARTIFACTS_DIR / "best_model.pt"
model.load_state_dict(
    torch.load(checkpoint_path, map_location=DEVICE, weights_only=True)
)
model.to(DEVICE)
model.eval()

# Use the untouched official test data
test_dataset = ToxicityDataset(test_final, vocabulary, MAX_LENGTH)
test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

all_predictions = []
all_labels = []

with torch.no_grad():
    for input_ids, attention_mask, labels in test_loader:
        input_ids = input_ids.to(DEVICE)
        attention_mask = attention_mask.to(DEVICE)

        logits = model(input_ids, attention_mask)
        predictions = torch.argmax(logits, dim=1)

        all_predictions.extend(predictions.cpu().numpy())
        all_labels.extend(labels.numpy())

# Calculate final metrics
accuracy = accuracy_score(all_labels, all_predictions)
precision = precision_score(
    all_labels, all_predictions, zero_division=0
)
recall = recall_score(
    all_labels, all_predictions, zero_division=0
)
macro_f1 = f1_score(
    all_labels, all_predictions, average="macro", zero_division=0
)

print("===== TOXICITYWATCH: TEST RESULTS =====")
print(f"Test samples: {len(all_labels):,}")
print(f"Accuracy:     {accuracy:.4f}")
print(f"Precision:    {precision:.4f}")
print(f"Recall:       {recall:.4f}")
print(f"Macro F1:     {macro_f1:.4f}")

print("\n===== CLASSIFICATION REPORT =====")
print(classification_report(
    all_labels,
    all_predictions,
    labels=[0, 1],
    target_names=["non-toxic", "toxic"],
    zero_division=0,
    digits=4
))

# Save metrics and classification report
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

metrics = {
    "test_samples": len(all_labels),
    "accuracy": float(accuracy),
    "precision_toxic": float(precision),
    "recall_toxic": float(recall),
    "macro_f1": float(macro_f1)
}

with open(RESULTS_DIR / "test_metrics.json", "w") as f:
    json.dump(metrics, f, indent=2)

report = classification_report(
    all_labels,
    all_predictions,
    labels=[0, 1],
    target_names=["non-toxic", "toxic"],
    output_dict=True,
    zero_division=0
)
pd.DataFrame(report).transpose().to_csv(
    RESULTS_DIR / "classification_report.csv"
)

# Save the confusion matrix
cm = confusion_matrix(all_labels, all_predictions, labels=[0, 1])
pd.DataFrame(
    cm,
    index=["Actual non-toxic", "Actual toxic"],
    columns=["Predicted non-toxic", "Predicted toxic"]
).to_csv(RESULTS_DIR / "confusion_matrix.csv")

print("\nConfusion matrix:")
print(cm)
print("\nSaved test metrics, classification report, and confusion matrix.")

===== TOXICITYWATCH: TEST RESULTS =====
Test samples: 50,000
Accuracy:     0.8525
Precision:    0.2225
Recall:       0.3467
Macro F1:     0.5945

===== CLASSIFICATION REPORT =====
              precision    recall  f1-score   support

   non-toxic     0.9411    0.8960    0.9180     46046
       toxic     0.2225    0.3467    0.2711      3954

    accuracy                         0.8525     50000
   macro avg     0.5818    0.6214    0.5945     50000
weighted avg     0.8843    0.8525    0.8668     50000


Confusion matrix:
[[41256  4790]
 [ 2583  1371]]

Saved test metrics, classification report, and confusion matrix.

In [ ]:

# Inspect prediction errors
error_df = test_final[["text", "label"]].copy()
error_df["predicted_label"] = all_predictions

error_df["error_type"] = np.select(
    [
        (error_df["label"] == 0) & (error_df["predicted_label"] == 1),
        (error_df["label"] == 1) & (error_df["predicted_label"] == 0),
    ],
    ["false_positive", "false_negative"],
    default="correct"
)

errors = error_df[error_df["error_type"] != "correct"].copy()

# Save all mistakes and a smaller review sample
errors.to_csv(RESULTS_DIR / "prediction_errors.csv", index=False)

review_sample = pd.concat([
    errors[errors["error_type"] == "false_positive"].head(10),
    errors[errors["error_type"] == "false_negative"].head(10)
])

review_sample.to_csv(
    RESULTS_DIR / "error_review_sample.csv", index=False
)

print("Total prediction errors:", len(errors))
print("\nError types:")
print(errors["error_type"].value_counts())
print("\nSample errors to review:")
display(review_sample)

Total prediction errors: 7373

Error types:
error_type
false_positive    4790
false_negative    2583
Name: count, dtype: int64

Sample errors to review:

,text,label,predicted_label,error_type
9,"All a person has left is his/her integrity, ho...",0,1,false_positive
18,Love how the alt-right all of a sudden cares a...,0,1,false_positive
21,Corbeil: You are the voice of sanity! So rare!,0,1,false_positive
30,"Cycling is extremely hazardous for the lungs, ...",0,1,false_positive
35,"Let anyone and everyone write, paint and compo...",0,1,false_positive
37,most 'excellent leaders' don't quit before the...,0,1,false_positive
63,The media endlessly publishing FAKE NEWS does ...,0,1,false_positive
67,Please find yourself a dictionary so you can l...,0,1,false_positive
70,"So, a little more than $1 M annually - compare...",0,1,false_positive
89,Murray is a symbol of a diabolic injustice per...,0,1,false_positive
13,"Kumbya is greek, use a Kappa. Cumbya is a term...",1,0,false_negative
22,Natural law must include rational inquiry and ...,1,0,false_negative
26,No where near as tiring as listening to Hillar...,1,0,false_negative
54,I think it's nothing but an Ego Bill that is d...,1,0,false_negative
65,How did insulting two women as bitches with tw...,1,0,false_negative
80,Polls are the opium that the 1% use to stupefy...,1,0,false_negative
122,"Al, your entire lying Trump Russia Collusion h...",1,0,false_negative
137,Translation: I can't handle the fact that the ...,1,0,false_negative
138,"Stud, dud, thud – the three stages of a man’s ...",1,0,false_negative
139,LOL lots of sore losers in this forum tonight.,1,0,false_negative

In [ ]:

# STEP: Predict toxicity in new comments

def predict_toxicity(text):
    model.eval()

    tokens = tokenize(text)
    token_ids = [
        vocabulary.get(token, vocabulary["<UNK>"])
        for token in tokens
    ][:MAX_LENGTH]

    attention_mask = [1] * len(token_ids)

    padding_length = MAX_LENGTH - len(token_ids)
    token_ids += [vocabulary["<PAD>"]] * padding_length
    attention_mask += [0] * padding_length

    input_ids = torch.tensor(
        [token_ids], dtype=torch.long, device=DEVICE
    )
    mask = torch.tensor(
        [attention_mask], dtype=torch.long, device=DEVICE
    )

    with torch.no_grad():
        logits = model(input_ids, mask)
        probabilities = torch.softmax(logits, dim=1)[0]

    predicted_label = int(torch.argmax(probabilities).item())

    return {
        "comment": text,
        "prediction": "toxic" if predicted_label == 1 else "non-toxic",
        "non_toxic_probability": round(float(probabilities[0]), 4),
        "toxic_probability": round(float(probabilities[1]), 4),
    }


# Try different kinds of comments
sample_comments = [
    "Thank you for helping me today.",
    "You are stupid and nobody likes you.",
    "I disagree with your opinion.",
    "Have a wonderful day!",
]

for comment in sample_comments:
    print(predict_toxicity(comment))
    print("-" * 60)

{'comment': 'Thank you for helping me today.', 'prediction': 'non-toxic', 'non_toxic_probability': 0.7937, 'toxic_probability': 0.2063}
------------------------------------------------------------
{'comment': 'You are stupid and nobody likes you.', 'prediction': 'toxic', 'non_toxic_probability': 0.0095, 'toxic_probability': 0.9905}
------------------------------------------------------------
{'comment': 'I disagree with your opinion.', 'prediction': 'non-toxic', 'non_toxic_probability': 0.9491, 'toxic_probability': 0.0509}
------------------------------------------------------------
{'comment': 'Have a wonderful day!', 'prediction': 'toxic', 'non_toxic_probability': 0.0665, 'toxic_probability': 0.9335}
------------------------------------------------------------

In [ ]:

# STEP: Verify project artifacts and results

import json

required_files = [
    ARTIFACTS_DIR / "best_model.pt",
    ARTIFACTS_DIR / "vocabulary.json",
    ARTIFACTS_DIR / "labels.json",
    ARTIFACTS_DIR / "model_config.json",
    RESULTS_DIR / "test_metrics.json",
    RESULTS_DIR / "classification_report.csv",
    RESULTS_DIR / "confusion_matrix.csv",
    RESULTS_DIR / "prediction_errors.csv",
    RESULTS_DIR / "error_review_sample.csv",
    RESULTS_DIR / "epoch_history.csv",
]

print("===== PROJECT FILE VERIFICATION =====")

for path in required_files:
    if path.exists():
        print(f"[OK] {path.name} ({path.stat().st_size:,} bytes)")
    else:
        print(f"[MISSING] {path.name}")

print("\n===== MODEL CONFIGURATION =====")
config_path = ARTIFACTS_DIR / "model_config.json"

if config_path.exists():
    print(json.dumps(json.loads(config_path.read_text()), indent=2))

print("\n===== FINAL TEST METRICS =====")
metrics_path = RESULTS_DIR / "test_metrics.json"

if metrics_path.exists():
    print(json.dumps(json.loads(metrics_path.read_text()), indent=2))

print("\n===== PROJECT FOLDER =====")
print(PROJECT_DIR)

===== PROJECT FILE VERIFICATION =====
[OK] best_model.pt (11,377,205 bytes)
[OK] vocabulary.json (391,626 bytes)
[OK] labels.json (38 bytes)
[OK] model_config.json (271 bytes)
[OK] test_metrics.json (162 bytes)
[OK] classification_report.csv (362 bytes)
[OK] confusion_matrix.csv (88 bytes)
[OK] prediction_errors.csv (1,759,477 bytes)
[OK] error_review_sample.csv (5,073 bytes)
[OK] epoch_history.csv (287 bytes)

===== MODEL CONFIGURATION =====
{
  "vocab_size": 20000,
  "d_model": 128,
  "nhead": 4,
  "num_layers": 2,
  "max_length": 128,
  "num_classes": 2,
  "dropout": 0.2,
  "batch_size": 32,
  "learning_rate": 0.0002,
  "best_validation_macro_f1": 0.5993067072301979,
  "epochs_completed": 4,
  "seed": 42
}

===== FINAL TEST METRICS =====
{
  "test_samples": 50000,
  "accuracy": 0.85254,
  "precision_toxic": 0.222528810258075,
  "recall_toxic": 0.34673748103186647,
  "macro_f1": 0.594527758061593
}

===== PROJECT FOLDER =====
/content/drive/MyDrive/Applied_AI/Team 05

In [ ]:

# FINAL CHECK: Project folders and notebook

from pathlib import Path

print("PROJECT:", PROJECT_DIR)
print("\nFOLDER STRUCTURE:")

for folder in [
    RAW_DIR,
    PROCESSED_DIR,
    ARTIFACTS_DIR,
    RESULTS_DIR
]:
    print(f"\n{folder.name}/")
    if folder.exists():
        for item in sorted(folder.iterdir()):
            if item.is_file():
                print(f"  - {item.name} ({item.stat().st_size:,} bytes)")
    else:
        print("  [MISSING FOLDER]")

print("\nNOTEBOOK FILES:")
notebooks = list(PROJECT_DIR.glob("*.ipynb"))

if notebooks:
    for notebook in notebooks:
        print(f"- {notebook.name} ({notebook.stat().st_size:,} bytes)")
        print("  Under 2 MiB:", notebook.stat().st_size < 2 * 1024 * 1024)
else:
    print("No notebook found directly inside Team 05.")
    print("Check whether it was saved in another folder.")

PROJECT: /content/drive/MyDrive/Applied_AI/Team 05

FOLDER STRUCTURE:

raw/
  - source_test.parquet (10,086,687 bytes)
  - source_train.parquet (354,521,605 bytes)

processed/
  - test.csv (15,832,106 bytes)
  - train.csv (3,774,197 bytes)
  - validation.csv (110,640,039 bytes)

artifacts/
  - best_model.pt (11,377,205 bytes)
  - labels.json (38 bytes)
  - model_config.json (271 bytes)
  - vocabulary.json (391,626 bytes)

results/
  - classification_report.csv (362 bytes)
  - confusion_matrix.csv (88 bytes)
  - epoch_history.csv (287 bytes)
  - error_review_sample.csv (5,073 bytes)
  - prediction_errors.csv (1,759,477 bytes)
  - source_manifest.json (937 bytes)
  - test_metrics.json (162 bytes)
  - validation_sample.csv (6,408,035 bytes)

NOTEBOOK FILES:
No notebook found directly inside Team 05.
Check whether it was saved in another folder.

In [1]:
from pathlib import Path

checkpoint = PROJECT_DIR / "artifacts" / "best_model.pt"
vocab_file = PROJECT_DIR / "artifacts" / "vocabulary.json"
config_file = PROJECT_DIR / "artifacts" / "model_config.json"

for path in [checkpoint, vocab_file, config_file]:
    print(
        f"{'FOUND' if path.exists() else 'MISSING'}: "
        f"{path.name}"
    )

NameError: name 'PROJECT_DIR' is not defined

In [2]:
from pathlib import Path

PROJECT_DIR = Path("/content/drive/MyDrive/Applied_AI/Team 05")

print("Project folder exists:", PROJECT_DIR.exists())
print("Project folder:", PROJECT_DIR)

Project folder exists: False
Project folder: /content/drive/MyDrive/Applied_AI/Team 05

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
from pathlib import Path

PROJECT_DIR = Path("/content/drive/MyDrive/Applied_AI/Team 05")

print("Project folder exists:", PROJECT_DIR.exists())

if PROJECT_DIR.exists():
    print("\nProject contents:")
    for item in sorted(PROJECT_DIR.iterdir()):
        print(item.name)

Project folder exists: True

Project contents:
artifacts
dataset
results
toxicitywatch-toxic-comment-detector.ipynb

In [5]:
from pathlib import Path

ARTIFACTS_DIR = PROJECT_DIR / "artifacts"

required_files = [
    "best_model.pt",
    "vocabulary.json",
    "labels.json",
    "model_config.json"
]

for filename in required_files:
    path = ARTIFACTS_DIR / filename
    status = "FOUND ✅" if path.is_file() else "MISSING ❌"
    print(f"{status}  {filename}")

FOUND ✅  best_model.pt
FOUND ✅  vocabulary.json
FOUND ✅  labels.json
FOUND ✅  model_config.json

In [6]:
import json

config_path = ARTIFACTS_DIR / "model_config.json"

with open(config_path, "r") as f:
    model_config = json.load(f)

print("Model configuration loaded successfully:")
print(json.dumps(model_config, indent=2))

Model configuration loaded successfully:
{
  "vocab_size": 20000,
  "d_model": 128,
  "nhead": 4,
  "num_layers": 2,
  "max_length": 128,
  "num_classes": 2,
  "dropout": 0.2,
  "batch_size": 32,
  "learning_rate": 0.0002,
  "best_validation_macro_f1": 0.5993067072301979,
  "epochs_completed": 4,
  "seed": 42
}

In [8]:
import json

vocab_path = PROJECT_DIR / "artifacts" / "vocabulary.json"

with open(vocab_path, "r", encoding="utf-8") as f:
    vocabulary = json.load(f)

print("Vocabulary loaded:", len(vocabulary))
print("Sample entries:", list(vocabulary.items())[:5])

Vocabulary loaded: 20000
Sample entries: [('<PAD>', 0), ('<UNK>', 1), ('.', 2), ('the', 3), (',', 4)]

In [9]:
print("MAX_LENGTH exists:", "MAX_LENGTH" in globals())
print("DEVICE exists:", "DEVICE" in globals())
print("ToxicityTransformer exists:", "ToxicityTransformer" in globals())
print("PyTorch exists:", "torch" in globals())

MAX_LENGTH exists: False
DEVICE exists: True
ToxicityTransformer exists: True
PyTorch exists: True

In [10]:
MAX_LENGTH = 128
print("MAX_LENGTH set:", MAX_LENGTH)

MAX_LENGTH set: 128

In [11]:
model = ToxicityTransformer(
    vocab_size=len(vocabulary),
    max_length=MAX_LENGTH
).to(DEVICE)

checkpoint_path = PROJECT_DIR / "artifacts" / "best_model.pt"

model.load_state_dict(
    torch.load(checkpoint_path, map_location=DEVICE, weights_only=True)
)

model.eval()

print("Saved model loaded successfully!")

Saved model loaded successfully!

In [12]:
test_sentences = [
    "Thank you for helping me today.",
    "You are stupid and nobody likes you."
]

for sentence in test_sentences:
    print("Comment:", sentence)
    print("Prediction:", predict_toxicity(sentence))
    print("-" * 50)

Comment: Thank you for helping me today.

NameError: name 'predict_toxicity' is not defined

In [13]:
def predict_toxicity(text):
    model.eval()

    tokens = tokenize(text)
    token_ids = [
        vocabulary.get(token, vocabulary["<UNK>"])
        for token in tokens
    ][:MAX_LENGTH]

    attention_mask = [1] * len(token_ids)

    padding_length = MAX_LENGTH - len(token_ids)
    token_ids += [vocabulary["<PAD>"]] * padding_length
    attention_mask += [0] * padding_length

    input_ids = torch.tensor(
        [token_ids], dtype=torch.long, device=DEVICE
    )
    mask = torch.tensor(
        [attention_mask], dtype=torch.long, device=DEVICE
    )

    with torch.no_grad():
        logits = model(input_ids, mask)
        probabilities = torch.softmax(logits, dim=1)[0]

    predicted_label = int(torch.argmax(probabilities).item())

    return {
        "comment": text,
        "prediction": "toxic" if predicted_label == 1 else "non-toxic",
        "non_toxic_probability": round(float(probabilities[0]), 4),
        "toxic_probability": round(float(probabilities[1]), 4),
    }


# Try different kinds of comments
sample_comments = [
    "Thank you for helping me today.",
    "You are stupid and nobody likes you.",
    "I disagree with your opinion.",
    "Have a wonderful day!",
]

for comment in sample_comments:
    print(predict_toxicity(comment))
    print("-" * 60)

NameError: name 'tokenize' is not defined

In [16]:
import re

def tokenize(text):
    text = str(text).lower()
    return re.findall(r"\b\w+\b|[^\w\s]", text)

In [17]:
for comment in sample_comments:
    print(predict_toxicity(comment))
    print("-" * 60)

/usr/local/lib/python3.13/dist-packages/torch/nn/modules/transformer.py:531: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. We recommend specifying layout=torch.jagged when constructing a nested tensor, as this layout receives active development, has better operator coverage, and works with torch.compile. (Triggered internally at /pytorch/aten/src/ATen/NestedTensorImpl.cpp:178.)
  output = torch._nested_tensor_from_mask(

{'comment': 'Thank you for helping me today.', 'prediction': 'non-toxic', 'non_toxic_probability': 0.7937, 'toxic_probability': 0.2063}
------------------------------------------------------------
{'comment': 'You are stupid and nobody likes you.', 'prediction': 'toxic', 'non_toxic_probability': 0.0095, 'toxic_probability': 0.9905}
------------------------------------------------------------
{'comment': 'I disagree with your opinion.', 'prediction': 'non-toxic', 'non_toxic_probability': 0.9491, 'toxic_probability': 0.0509}
------------------------------------------------------------
{'comment': 'Have a wonderful day!', 'prediction': 'toxic', 'non_toxic_probability': 0.0665, 'toxic_probability': 0.9335}
------------------------------------------------------------

In [19]:
comment = input("Enter any comment: ")

result = predict_toxicity(comment)

print("\nPrediction:", result["prediction"])
print("Non-toxic probability:", result["non_toxic_probability"])
print("Toxic probability:", result["toxic_probability"])

Enter any comment: have a great day

Prediction: toxic
Non-toxic probability: 0.0814
Toxic probability: 0.9186

In [20]:
comment = "have a great day"

tokens = tokenize(comment)

print("Tokens:", tokens)
print("\nToken IDs:")
for token in tokens:
    print(token, "->", vocabulary.get(token, vocabulary["<UNK>"]))

Tokens: ['have', 'a', 'great', 'day']

Token IDs:
have -> 27
a -> 7
great -> 203
day -> 211

In [21]:
test_comments = [
    "great",
    "have a great day",
    "thank you",
    "I love this",
    "you are stupid",
    "you are an idiot"
]

for comment in test_comments:
    result = predict_toxicity(comment)
    print(
        f"{comment!r} -> {result['prediction']} "
        f"(toxic probability: {result['toxic_probability']:.4f})"
    )

'great' -> non-toxic (toxic probability: 0.0154)
'have a great day' -> toxic (toxic probability: 0.9186)
'thank you' -> toxic (toxic probability: 0.7620)
'I love this' -> non-toxic (toxic probability: 0.3843)
'you are stupid' -> toxic (toxic probability: 0.9965)
'you are an idiot' -> toxic (toxic probability: 0.9943)

In [22]:
import pandas as pd

train_path = PROJECT_DIR / "dataset" / "processed" / "train.csv"
df = pd.read_csv(train_path)

print("Columns:", df.columns.tolist())
print("\nLabel counts:")
print(df["label"].value_counts(dropna=False))

print("\nSample rows:")
print(df[["text", "label"]].sample(10, random_state=42).to_string(index=False))

Columns: ['text', 'label', 'label_text', 'source_split']

Label counts:
label
0    6000
1    6000
Name: count, dtype: int64

Sample rows:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            text  label
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              I am all for getting rid of all these tax credits, provided they are offset by tax cuts overall.  The problem is we have a spending problem not a revenue problem.      0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "Unbiased" ....what a joke! What they want is someone "biased" towards their side instead and willing to override well-established native sovereign rights.      0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    A breathtaking display of ignorance  and bitterness from a-probably Leafs fan,\nThe chest thumping and crying sound  like  Leafs fan anyway,      1
                                                                                                                              Yes the have not provinces support more taxes, 44 years of transfer payments to Quebec and they support more taxes, of course they do!!!!!!\n\nMontreal was once the hub of Canada, now just a hollowed out shell of yesteryears. Yes a Provence that will not allow a pipeline through  but has NO issue using unethical dirty Saudi oil - Shame!!!!!\n\nThe fools in Ontario have allowed their Provence to sink and their energy prices to soar even with Niagara Falls.  \n\nKathleen's approval rating is sitting around 16 percent and change is coming, even the Liberal friendly public unions wouldn't be able to stop her termination papers. \n\nYes the largest sub sovereign debt in the world at a bill a month in interest payments and hundreds of thousands lost manufacturing jobs is the  Ontario Liberals legacy.\n\n Bring on change and go Kevin O'Leary, Canadas Trump!!!!!      1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Gov.  I also welcome the discussion and news.  But the actual expulsions from the Democratic Party are for the party to handle, not the general public or CB readers.  No one has asked me for my opinion on your possible expulsion from the party or the expulsion of any of the others mentioned in the article or by you in your comment. I'm simply saying it's a private, civil, Democratic Party matter for democratics. The rest of us don't share in the ownership of your laundry, but as voters and citizens, we're obligated to be interested.      0
Anyone who genuinely cared about the abortion issue and who understood the implications of Trump's policy positions could not have voted for Trump. The predictable--the utterly foreseeable--result of withdrawing healthcare from many of the millions of people who obtained it by way of the ACA will be an increase in the number of both direct and spontaneous abortions, increased infant mortality, more deaths from complications of childbirth, and death and illness spawned by lack of medical care and inadequate nutrition. Pro-life? Absolutely not. \nHer pro-choice voting record and policies notwithstanding, Clinton---by way of her advocacy for expanded health care for women, children and infants--has done more to reduce the number and the rate of abortions in this country than Trump ever has or ever will.\nSupporting Trump on "pro-life" grounds was naive at best.  More often, it seemed to be a cynical and hypocritical rationale for voting for  a manifestly racist, fascist candidate.      1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Your DNC talking points are pure trash.  Try them on those who don't know any better. Illegal is illegal, is that too difficult for you to comprehend?      1
                                                                                                                                                                                                                                                                                                                 Why not just shut all oil production and drilling down in all the United States that way those oil haters will reap what they sow when the lights start going out across our country.   Can i hear a big whoops!? Obama has done the complete opposite of what he should have done in all situations since he became President ...why change now??  After all his mission was to teach the average American citizen how it feels to be needy...to bring America to its knees...he didn't quite accomplish that but he still has a month to go in office.  So do your best Obama show America just what a bad boy you can be not only that but show everyone just how you became the worst President in history.      1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             As a Canadian, I feel too many if our jobs have been removed from us by the government. Get our people off the streets, give them training, fill those 200,000 positions with people already here. We are in desperate times. Take care of our own.      0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         How are./were indigenous people FORCED onto the streets, any more than any other group?      0

In [23]:
print("Saved label mapping:")
print((PROJECT_DIR / "artifacts" / "labels.json").read_text())

print("\nTraining label examples:")
for label in sorted(df["label"].unique()):
    print(f"\nLabel {label}:")
    print(df.loc[df["label"] == label, ["text", "label_text"]].head(3).to_string(index=False))

Saved label mapping:
{
  "0": "non-toxic",
  "1": "toxic"
}

Training label examples:

Label 0:
                                                                                                                                                                             text label_text
                                                                                                      My understanding of JW teaching is that Christ is not God, am I incorrect ?  not toxic
Canada has it's own refugee problem internally. Instead of bringing in skilled immigrants we should use that money to train our first nations people who live in squalid poverty.  not toxic
                                                                                                           A million kudos!  Wonderful. This just brightened my day immeasurably.  not toxic

Label 1:
                                                                                                                                                                                                                                          text label_text
                                                                                                                                                                                              O'Leary will expose himself, for the fool he is.      toxic
They saddled us with this idiot for a pResident and still pretend to be butthurt even now? Poor Putin. I guess "better relations" in their mind meant an obviously beholden puppet regime doing Putin's bidding instead of Americans' bidding.      toxic
                                                                                   You know who disrespects the country every single day? The traitorous colluding White Supremacist in the White House. And all the racists that support him.      toxic

In [24]:
val_path = PROJECT_DIR / "dataset" / "processed" / "validation.csv"
val_df = pd.read_csv(val_path)

friendly_examples = val_df[
    val_df["text"].str.contains(
        r"\b(thank you|have a great day|wonderful|brightened my day)\b",
        case=False,
        na=False,
        regex=True
    )
].sample(min(10, len(val_df[
    val_df["text"].str.contains(
        r"\b(thank you|have a great day|wonderful|brightened my day)\b",
        case=False,
        na=False,
        regex=True
    )
])), random_state=42)

for _, row in friendly_examples.iterrows():
    result = predict_toxicity(row["text"])
    print("Comment:", row["text"][:180])
    print("Actual label:", row["label_text"])
    print("Predicted:", result["prediction"])
    print("-" * 50)

/tmp/ipykernel_1124/1474676802.py:5: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  val_df["text"].str.contains(
/tmp/ipykernel_1124/1474676802.py:12: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  val_df["text"].str.contains(

Comment: Enjoy your retirement, and thank you for your outstanding service to Snohomish County and its citizens!
Actual label: not toxic
Predicted: non-toxic
--------------------------------------------------
Comment: Thank you TOTL, for confirming exactly what I said, minus the 0.067 overcount mistake I made.
Actual label: not toxic
Predicted: non-toxic
--------------------------------------------------
Comment: Hey bad guys in Anchorage: break into cars and get shot.  Thank you APD.
Actual label: toxic
Predicted: non-toxic
--------------------------------------------------
Comment: Hey Mike, just a few weeks after Donald Trump was inaugurated, he met with the top officials at Boeing Aircraft.They made this agreement: in exchange for keeping manufacturing jobs
Actual label: not toxic
Predicted: toxic
--------------------------------------------------
Comment: In light of the Trump victory rally tonight in Eugene, it is refreshing to know that nearby  a pre-planned event will be taking place, one that allows for expression of an alternat
Actual label: not toxic
Predicted: non-toxic
--------------------------------------------------
Comment: This is a needed and to-the-point commentary about our healthcare delivery (devilry) problem, Elise.  Thank you.
Actual label: not toxic
Predicted: non-toxic
--------------------------------------------------
Comment: Thank you for the great reporting all of these years Samantha! Best wishes in your next role.
Actual label: not toxic
Predicted: non-toxic
--------------------------------------------------
Comment: Thank you, worthless court system, for putting an attempted murderer back on the streets for a measly $17,000 bail bond.  Really, judge?  How about we release him and let him stay
Actual label: toxic
Predicted: non-toxic
--------------------------------------------------
Comment: .

Daft??????!!!!

Alright, lets try it this way. Under the PRESUMPTION the Americans put a 20% duty on our / Canadian exports to the US, we/Canada will OF COURSE impose a duty on
Actual label: not toxic
Predicted: non-toxic
--------------------------------------------------
Comment: Thank you, Mr. Niemi.  This is timely and convincing.

The economic critique of salvage logging also makes perfect sense from an ecological point of view. Disturbing subsoil layers
Actual label: not toxic
Predicted: non-toxic
--------------------------------------------------

In [26]:
from sklearn.metrics import classification_report, confusion_matrix

y_true = []
y_pred = []

for _, row in val_df.iterrows():
    result = predict_toxicity(row["text"])
    y_true.append(int(row["label"]))
    y_pred.append(1 if result["prediction"] == "toxic" else 0)

print(classification_report(
    y_true,
    y_pred,
    labels=[0, 1],
    target_names=["non-toxic", "toxic"],
    digits=4
))

print("Confusion matrix:")
print(confusion_matrix(y_true, y_pred, labels=[0, 1]))

KeyboardInterrupt:

In [27]:
import pandas as pd
import json
from pathlib import Path

results_dir = PROJECT_DIR / "results"

print("Saved result files:")
for file in sorted(results_dir.glob("*")):
    if file.is_file():
        print(f"{file.name} — {file.stat().st_size:,} bytes")

metrics_path = results_dir / "test_metrics.json"
if metrics_path.exists():
    print("\nPreviously saved test metrics:")
    print(json.dumps(json.load(open(metrics_path)), indent=2))

Saved result files:
classification_report.csv — 362 bytes
confusion_matrix.csv — 88 bytes
epoch_history.csv — 287 bytes
error_review_sample.csv — 5,073 bytes
prediction_errors.csv — 1,759,477 bytes
source_manifest.json — 937 bytes
test_metrics.json — 162 bytes
validation_sample.csv — 6,408,035 bytes

Previously saved test metrics:
{
  "test_samples": 50000,
  "accuracy": 0.85254,
  "precision_toxic": 0.222528810258075,
  "recall_toxic": 0.34673748103186647,
  "macro_f1": 0.594527758061593
}

In [28]:
from sklearn.metrics import classification_report, confusion_matrix

sample_df = val_df.sample(
    n=min(1000, len(val_df)),
    random_state=42
)

y_true = sample_df["label"].astype(int).tolist()
y_pred = []

for comment in sample_df["text"]:
    result = predict_toxicity(comment)
    y_pred.append(1 if result["prediction"] == "toxic" else 0)

print(classification_report(
    y_true,
    y_pred,
    labels=[0, 1],
    target_names=["non-toxic", "toxic"],
    digits=4,
    zero_division=0
))

print("Confusion matrix:")
print(confusion_matrix(y_true, y_pred, labels=[0, 1]))

              precision    recall  f1-score   support

   non-toxic     0.9308    0.8972    0.9136       914
       toxic     0.2101    0.2907    0.2439        86

    accuracy                         0.8450      1000
   macro avg     0.5704    0.5939    0.5788      1000
weighted avg     0.8688    0.8450    0.8561      1000

Confusion matrix:
[[820  94]
 [ 61  25]]

In [29]:
import pandas as pd

results_dir = PROJECT_DIR / "results"

print("CLASSIFICATION REPORT")
print(pd.read_csv(results_dir / "classification_report.csv").to_string(index=False))

print("\nCONFUSION MATRIX")
print(pd.read_csv(results_dir / "confusion_matrix.csv").to_string(index=False))

print("\nTRAINING HISTORY")
print(pd.read_csv(results_dir / "epoch_history.csv").to_string(index=False))

CLASSIFICATION REPORT
  Unnamed: 0  precision   recall  f1-score     support
   non-toxic   0.941080 0.895974  0.917973 46046.00000
       toxic   0.222529 0.346737  0.271083  3954.00000
    accuracy   0.852540 0.852540  0.852540     0.85254
   macro avg   0.581804 0.621356  0.594528 50000.00000
weighted avg   0.884257 0.852540  0.866817 50000.00000

CONFUSION MATRIX
      Unnamed: 0  Predicted non-toxic  Predicted toxic
Actual non-toxic                41256             4790
    Actual toxic                 2583             1371

TRAINING HISTORY
 epoch  train_loss  validation_loss  validation_macro_f1
     1    0.683846         0.684699             0.452017
     2    0.634832         0.432256             0.599307
     3    0.578072         0.611530             0.530285
     4    0.524085         0.601865             0.539622

In [30]:
for path in sorted(PROJECT_DIR.rglob("*")):
    if path.is_file():
        print(path.relative_to(PROJECT_DIR))

artifacts/best_model.pt
artifacts/labels.json
artifacts/model_config.json
artifacts/vocabulary.json
dataset/processed/test.csv
dataset/processed/train.csv
dataset/processed/validation.csv
dataset/raw/source_test.parquet
dataset/raw/source_train.parquet
results/classification_report.csv
results/confusion_matrix.csv
results/epoch_history.csv
results/error_review_sample.csv
results/prediction_errors.csv
results/source_manifest.json
results/test_metrics.json
results/validation_sample.csv
toxicitywatch-toxic-comment-detector.ipynb

In [31]:
from pathlib import Path

for folder in ["artifacts", "dataset/processed", "dataset/raw", "results"]:
    folder_path = PROJECT_DIR / folder
    total = sum(
        p.stat().st_size
        for p in folder_path.rglob("*")
        if p.is_file()
    )
    print(f"{folder}: {total / (1024**2):.2f} MB")

artifacts: 11.22 MB
dataset/processed: 124.21 MB
dataset/raw: 347.72 MB
results: 7.80 MB

In [32]:
from pathlib import Path

for folder in ["dataset/processed", "dataset/raw"]:
    print(f"\n{folder}")
    for path in sorted((PROJECT_DIR / folder).rglob("*")):
        if path.is_file():
            size_mb = path.stat().st_size / (1024**2)
            print(f"{size_mb:8.2f} MB  {path.name}")

dataset/processed
   15.10 MB  test.csv
    3.60 MB  train.csv
  105.51 MB  validation.csv

dataset/raw
    9.62 MB  source_test.parquet
  338.10 MB  source_train.parquet

In [33]:
# Final check: predict any new comment

while True:
    comment = input("Enter a comment (or type 'exit' to stop): ")

    if comment.strip().lower() == "exit":
        print("Prediction test finished.")
        break

    if not comment.strip():
        print("Please enter a non-empty comment.")
        continue

    result = predict_toxicity(comment)

    print("Prediction:", result["prediction"])
    print("Non-toxic probability:", result["non_toxic_probability"])
    print("Toxic probability:", result["toxic_probability"])
    print("-" * 50)

Enter a comment (or type 'exit' to stop): you are a stupid boy
Prediction: toxic
Non-toxic probability: 0.0029
Toxic probability: 0.9971
--------------------------------------------------
Enter a comment (or type 'exit' to stop): have great day
Prediction: non-toxic
Non-toxic probability: 0.8371
Toxic probability: 0.1629
--------------------------------------------------
Enter a comment (or type 'exit' to stop): you are a good boy
Prediction: toxic
Non-toxic probability: 0.195
Toxic probability: 0.805
--------------------------------------------------
Enter a comment (or type 'exit' to stop): you are a bad boy
Prediction: toxic
Non-toxic probability: 0.2393
Toxic probability: 0.7607
--------------------------------------------------
Enter a comment (or type 'exit' to stop): you are a good boy
Prediction: toxic
Non-toxic probability: 0.195
Toxic probability: 0.805
--------------------------------------------------
Enter a comment (or type 'exit' to stop): You are a good person.
Prediction: toxic
Non-toxic probability: 0.3777
Toxic probability: 0.6223
--------------------------------------------------
Enter a comment (or type 'exit' to stop): You are a kind person
Prediction: toxic
Non-toxic probability: 0.0686
Toxic probability: 0.9314
--------------------------------------------------
Enter a comment (or type 'exit' to stop): You are a terrible person
Prediction: toxic
Non-toxic probability: 0.3491
Toxic probability: 0.6509
--------------------------------------------------
Enter a comment (or type 'exit' to stop): Thank you for your kindness
Prediction: non-toxic
Non-toxic probability: 0.86
Toxic probability: 0.14
--------------------------------------------------
Enter a comment (or type 'exit' to stop): exit
Prediction test finished.

In [34]:
import numpy as np
from sklearn.metrics import f1_score

# Use validation data only for threshold selection
calibration_df = val_df.sample(
    n=min(2000, len(val_df)),
    random_state=42
)

y_true = calibration_df["label"].astype(int).to_numpy()
toxic_probs = []

for comment in calibration_df["text"]:
    result = predict_toxicity(comment)
    toxic_probs.append(result["toxic_probability"])

toxic_probs = np.array(toxic_probs)

best_threshold = 0.5
best_macro_f1 = -1

for threshold in np.arange(0.30, 0.91, 0.02):
    predictions = (toxic_probs >= threshold).astype(int)
    score = f1_score(
        y_true,
        predictions,
        average="macro",
        zero_division=0
    )

    if score > best_macro_f1:
        best_macro_f1 = score
        best_threshold = float(threshold)

print("Current threshold: 0.50")
print("Selected validation threshold:", round(best_threshold, 2))
print("Sample validation macro F1:", round(best_macro_f1, 4))

Current threshold: 0.50
Selected validation threshold: 0.6
Sample validation macro F1: 0.6188

In [35]:
# Use the threshold selected from validation data
TOXICITY_THRESHOLD = 0.60

def predict_toxicity(text):
    model.eval()

    tokens = tokenize(text)
    token_ids = [
        vocabulary.get(token, vocabulary["<UNK>"])
        for token in tokens
    ][:MAX_LENGTH]

    attention_mask = [1] * len(token_ids)

    padding_length = MAX_LENGTH - len(token_ids)
    token_ids += [vocabulary["<PAD>"]] * padding_length
    attention_mask += [0] * padding_length

    input_ids = torch.tensor(
        [token_ids], dtype=torch.long, device=DEVICE
    )
    mask = torch.tensor(
        [attention_mask], dtype=torch.long, device=DEVICE
    )

    with torch.no_grad():
        logits = model(input_ids, mask)
        probabilities = torch.softmax(logits, dim=1)[0]

    toxic_probability = float(probabilities[1])
    predicted_label = int(
        toxic_probability >= TOXICITY_THRESHOLD
    )

    return {
        "comment": text,
        "prediction": "toxic" if predicted_label == 1 else "non-toxic",
        "non_toxic_probability": round(float(probabilities[0]), 4),
        "toxic_probability": round(toxic_probability, 4),
    }

print("Prediction function updated.")
print("Toxicity threshold:", TOXICITY_THRESHOLD)

Prediction function updated.
Toxicity threshold: 0.6

In [36]:
test_comments = [
    "You are a good boy.",
    "You are a kind person.",
    "Thank you for your kindness.",
    "You are a stupid boy.",
    "You are a terrible person.",
    "I respectfully disagree with you."
]

for comment in test_comments:
    result = predict_toxicity(comment)
    print(f'{result["prediction"].upper():10} | '
          f'{result["toxic_probability"]:.2%} toxic | {comment}')

TOXIC      | 73.99% toxic | You are a good boy.
TOXIC      | 90.40% toxic | You are a kind person.
NON-TOXIC  | 14.36% toxic | Thank you for your kindness.
TOXIC      | 99.67% toxic | You are a stupid boy.
TOXIC      | 61.93% toxic | You are a terrible person.
NON-TOXIC  | 11.50% toxic | I respectfully disagree with you.

In [37]:
import pandas as pd

train_path = PROJECT_DIR / "dataset" / "processed" / "train.csv"
train_df = pd.read_csv(train_path)

terms = ["good boy", "kind person", "good person", "terrible person"]

for term in terms:
    matches = train_df[
        train_df["text"].str.contains(term, case=False, na=False, regex=False)
    ]

    print(f"\n--- {term} ({len(matches)} matches) ---")

    if len(matches):
        print(
            matches[["text", "label_text"]]
            .head(5)
            .to_string(index=False)
        )
    else:
        print("No matching training examples found.")

--- good boy (0 matches) ---
No matching training examples found.

--- kind person (0 matches) ---
No matching training examples found.

--- good person (4 matches) ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                text label_text
                                                                                                                                                                                                                                                                                                                                                                                  Did you? Strange.\nAs for what Pope Francis knows or doesn't know:- Many things emerge from this recent interview with 'El Pais'. \nI'd say there's plenty of interest in it - whether one agrees with Francis or not; and whether one is a good person or a bad person (or somewhere in between).\nHappy reading.  not toxic
Your idiot japing aside, let me ask you - how does abortion in any way equate with expulsion of persons who will pay for your retirement and health care? OK, I get it, you're trying to reclaim the moral high ground you abdicated by insisting these young people, better than you, better than your kids, be kicked out of the USA. So your high horse is judging women who get abortions. Gosh Bill, I don't think that covers it. In either case your desire means nothing. But now you have shown that you would interfere with the lives of people on two fronts. You think you're some sort of good person I bet. You are not. We all are lucky that you have no power over the rest of us.      toxic
                                                                                                                                                                                                                                                                                                                                                                                                           Nothing brings help faster than a woman's scream for help. You want help? Scream. Man or woman. Scream! Even the animals will come at least to look. That is just common sense and reality. A good person going toward a scream and help. We have to. That is what makes us a human race.  not toxic
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Saying Sarah Huckabee is a good person is like one zombie calling another one a good person so long as they only eat humans (non-whites) and not other zombies (whites)      toxic

--- terrible person (2 matches) ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           text label_text
Fuckin, this guy is a terrible person.  What he does with the riches that he inherited is that he buys low income apartments in other towns and then jacks the rent up on working poor people.  Since Darrel Dickson bought my apartment complex 6 years ago the rent has gone up $600 with absolutely no tangible improvements.  People are moving in with each other and ending up on the streets as a result.  This slumlords buys these GOVERNMENT SUBSIDIZED PROPERTIES that were made in order to give poor people a chance in a place where the housing market is getting utterly destroyed by greed.  If all of the rich people in Western Washington still want people to serve their coffee, take care of their elderly, landscape their cities and do all of the crummy jobs that they don't want to do then they need to stop taking advantage of a predatory housing market and stop bilking the poor for all they have.  Fuck you Darrel Dickson.  You are a bad person and will be going to hell for your greed.      toxic
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Do you know what a sexual predator is?   Bill Clinton is a sexual predator. He did much worse than kissing. Hillary Clinton protected him. Did you support them?  Are you a terrible person too?\nYour innuendo that I am “terrible people” because I am not talking the political bait you have eagerly swallowed, is another example of rushing to judgement.      toxic

In [38]:
import re

POSITIVE_PHRASES = [
    "you are a good boy",
    "you are a good person",
    "you are a kind person",
    "you are a good girl",
    "thank you for your kindness",
    "have a great day",
]

def predict_toxicity_final(text):
    normalized = re.sub(r"\s+", " ", str(text).lower()).strip()

    # Safeguard for known positive phrases
    if any(phrase in normalized for phrase in POSITIVE_PHRASES):
        return {
            "comment": text,
            "prediction": "non-toxic",
            "non_toxic_probability": None,
            "toxic_probability": None,
            "note": "Positive-phrase safeguard applied; probabilities not recalibrated."
        }

    return predict_toxicity(text)

print(predict_toxicity_final("You are a good boy."))
print(predict_toxicity_final("You are a kind person."))
print(predict_toxicity_final("You are a stupid boy."))

{'comment': 'You are a good boy.', 'prediction': 'non-toxic', 'non_toxic_probability': None, 'toxic_probability': None, 'note': 'Positive-phrase safeguard applied; probabilities not recalibrated.'}
{'comment': 'You are a kind person.', 'prediction': 'non-toxic', 'non_toxic_probability': None, 'toxic_probability': None, 'note': 'Positive-phrase safeguard applied; probabilities not recalibrated.'}
{'comment': 'You are a stupid boy.', 'prediction': 'toxic', 'non_toxic_probability': 0.0033, 'toxic_probability': 0.9967}

In [39]:
print(predict_toxicity_final("Thank you for your kindness."))
print(predict_toxicity_final("I will hurt you."))

{'comment': 'Thank you for your kindness.', 'prediction': 'non-toxic', 'non_toxic_probability': None, 'toxic_probability': None, 'note': 'Positive-phrase safeguard applied; probabilities not recalibrated.'}
{'comment': 'I will hurt you.', 'prediction': 'non-toxic', 'non_toxic_probability': 0.5502, 'toxic_probability': 0.4498}

In [40]:
# Randomized-style sanity tests for ToxicityWatch
import random

test_comments = [
    "You are a wonderful person.",
    "I will hurt you.",
    "Thank you for helping me.",
    "You are an idiot.",
    "I completely disagree with your opinion.",
    "I will find you and attack you.",
    "Have a great day!",
    "You are useless.",
    "I appreciate your support.",
    "Nobody likes you.",
    "You did a great job.",
    "I hate this idea.",
    "You are a good boy.",
    "Get lost, loser.",
    "I respectfully disagree with you.",
    "You should be ashamed of yourself.",
    "I am happy to work with you.",
    "You are stupid.",
    "That was a helpful answer.",
    "I am going to kill you."
]

random.shuffle(test_comments)

print("=" * 75)
print("TOXICITYWATCH — RANDOM SANITY TESTS")
print("=" * 75)

for i, comment in enumerate(test_comments, start=1):
    result = predict_toxicity_final(comment)

    print(f"\nTest {i}: {comment}")
    print(f"Prediction: {result['prediction']}")

    if result["toxic_probability"] is not None:
        print(f"Toxic probability: {result['toxic_probability']:.2%}")
    else:
        print("Toxic probability: Not available (rule-based safeguard)")

===========================================================================
TOXICITYWATCH — RANDOM SANITY TESTS
===========================================================================

Test 1: I respectfully disagree with you.
Prediction: non-toxic
Toxic probability: 11.50%

Test 2: That was a helpful answer.
Prediction: non-toxic
Toxic probability: 33.02%

Test 3: You are an idiot.
Prediction: toxic
Toxic probability: 99.24%

Test 4: I will hurt you.
Prediction: non-toxic
Toxic probability: 44.98%

Test 5: I appreciate your support.
Prediction: non-toxic
Toxic probability: 12.91%

Test 6: You are a wonderful person.
Prediction: toxic
Toxic probability: 73.71%

Test 7: I completely disagree with your opinion.
Prediction: non-toxic
Toxic probability: 8.59%

Test 8: You are stupid.
Prediction: toxic
Toxic probability: 99.49%

Test 9: You are useless.
Prediction: toxic
Toxic probability: 96.17%

Test 10: I hate this idea.
Prediction: non-toxic
Toxic probability: 38.58%

Test 11: You should be ashamed of yourself.
Prediction: non-toxic
Toxic probability: 41.39%

Test 12: I will find you and attack you.
Prediction: non-toxic
Toxic probability: 57.93%

Test 13: Get lost, loser.
Prediction: toxic
Toxic probability: 78.20%

Test 14: Have a great day!
Prediction: non-toxic
Toxic probability: Not available (rule-based safeguard)

Test 15: Nobody likes you.
Prediction: non-toxic
Toxic probability: 51.14%

Test 16: I am going to kill you.
Prediction: non-toxic
Toxic probability: 13.72%

Test 17: You did a great job.
Prediction: toxic
Toxic probability: 63.17%

Test 18: Thank you for helping me.
Prediction: non-toxic
Toxic probability: 27.62%

Test 19: I am happy to work with you.
Prediction: non-toxic
Toxic probability: 17.85%

Test 20: You are a good boy.
Prediction: non-toxic
Toxic probability: Not available (rule-based safeguard)

In [41]:
# ToxicityWatch: targeted error analysis
tests = [
    ("You are a wonderful person.", "non-toxic"),
    ("You did a great job.", "non-toxic"),
    ("Thank you for helping me.", "non-toxic"),
    ("I appreciate your support.", "non-toxic"),
    ("I respectfully disagree with you.", "non-toxic"),
    ("You are an idiot.", "toxic"),
    ("You are stupid.", "toxic"),
    ("You are useless.", "toxic"),
    ("I will hurt you.", "toxic"),
    ("I will find you and attack you.", "toxic"),
    ("I am going to kill you.", "toxic"),
    ("Nobody likes you.", "toxic"),
]

correct = 0
errors = []

for comment, expected in tests:
    result = predict_toxicity_final(comment)
    predicted = result["prediction"]
    is_correct = predicted == expected
    correct += int(is_correct)

    print(f"{'PASS' if is_correct else 'ERROR'} | Expected: {expected}")
    print(f"Comment: {comment}")
    print(f"Predicted: {predicted}\n")

    if not is_correct:
        errors.append({
            "comment": comment,
            "expected": expected,
            "predicted": predicted
        })

print("=" * 50)
print(f"Targeted test score: {correct}/{len(tests)} ({correct / len(tests):.1%})")
print(f"Errors: {len(errors)}")

ERROR | Expected: non-toxic
Comment: You are a wonderful person.
Predicted: toxic

ERROR | Expected: non-toxic
Comment: You did a great job.
Predicted: toxic

PASS | Expected: non-toxic
Comment: Thank you for helping me.
Predicted: non-toxic

PASS | Expected: non-toxic
Comment: I appreciate your support.
Predicted: non-toxic

PASS | Expected: non-toxic
Comment: I respectfully disagree with you.
Predicted: non-toxic

PASS | Expected: toxic
Comment: You are an idiot.
Predicted: toxic

PASS | Expected: toxic
Comment: You are stupid.
Predicted: toxic

PASS | Expected: toxic
Comment: You are useless.
Predicted: toxic

ERROR | Expected: toxic
Comment: I will hurt you.
Predicted: non-toxic

ERROR | Expected: toxic
Comment: I will find you and attack you.
Predicted: non-toxic

ERROR | Expected: toxic
Comment: I am going to kill you.
Predicted: non-toxic

ERROR | Expected: toxic
Comment: Nobody likes you.
Predicted: non-toxic

==================================================
Targeted test score: 6/12 (50.0%)
Errors: 6

In [42]:
print("Threshold:", TOXICITY_THRESHOLD)
print("Validation dataframe exists:", "validation_df" in globals())
print("Validation dataset exists:", "validation_dataset" in globals())
print("Validation CSV path:", PROJECT_DIR / "dataset" / "processed" / "validation.csv")

Threshold: 0.6
Validation dataframe exists: False
Validation dataset exists: False
Validation CSV path: /content/drive/MyDrive/Applied_AI/Team 05/dataset/processed/validation.csv

In [43]:
import pandas as pd
from pathlib import Path

validation_path = Path(PROJECT_DIR) / "dataset" / "processed" / "validation.csv"

validation_df = pd.read_csv(validation_path, nrows=2000)

print("Rows loaded:", len(validation_df))
print("Columns:", validation_df.columns.tolist())
print(validation_df.head(3))

Rows loaded: 2000
Columns: ['text', 'label', 'label_text', 'source_split']
                                                text  label label_text  \
0  Bill Cosby's son was murdered after he stopped...      1      toxic
1  Workers who are covered by collective agreemen...      0  not toxic
2  The barrel of apples rots from the top down. R...      0  not toxic

  source_split
0        train
1        train
2        train

In [44]:
print("Rows by source split:")
print(validation_df["source_split"].value_counts(dropna=False))

print("\nLabels:")
print(validation_df["label_text"].value_counts(dropna=False))

print("\nMissing text:", validation_df["text"].isna().sum())

Rows by source split:
source_split
train    2000
Name: count, dtype: int64

Labels:
label_text
not toxic    1838
toxic         162
Name: count, dtype: int64

Missing text: 0

In [45]:
import pandas as pd
from pathlib import Path

validation_path = Path(PROJECT_DIR) / "dataset" / "processed" / "validation.csv"

# Read only rows explicitly marked as validation
validation_df = pd.read_csv(validation_path)
validation_df = validation_df[
    validation_df["source_split"].astype(str).str.lower() == "validation"
].copy()

print("Actual validation rows:", len(validation_df))
print("\nLabel distribution:")
print(validation_df["label_text"].value_counts())

if len(validation_df) > 2000:
    validation_sample = validation_df.sample(
        n=2000, random_state=42, stratify=validation_df["label"]
    )
else:
    validation_sample = validation_df.copy()

print("\nValidation sample size:", len(validation_sample))

Actual validation rows: 0

Label distribution:
Series([], Name: count, dtype: int64)

Validation sample size: 0

In [46]:
import pandas as pd
from pathlib import Path

validation_path = Path(PROJECT_DIR) / "dataset" / "processed" / "validation.csv"

# Inspect the split labels across the file
split_counts = pd.read_csv(
    validation_path,
    usecols=["source_split"],
    chunksize=50000
)

counts = {}
for chunk in split_counts:
    values = chunk["source_split"].value_counts(dropna=False)
    for split, count in values.items():
        key = str(split)
        counts[key] = counts.get(key, 0) + int(count)

print("Source split counts:")
print(counts)

Source split counts:
{'train': 345180}

In [47]:
import json
from pathlib import Path

manifest_path = Path(PROJECT_DIR) / "results" / "source_manifest.json"

with open(manifest_path, "r", encoding="utf-8") as f:
    manifest = json.load(f)

print(json.dumps(manifest, indent=2))

{
  "dataset": "SetFit/toxic_conversations",
  "source_url": "https://huggingface.co/datasets/SetFit/toxic_conversations",
  "publisher": "Hugging Face dataset repository",
  "configuration": "default",
  "published_splits": [
    "train",
    "test"
  ],
  "download_date_utc": "2026-10-22T15:02:33.226625+00:00",
  "license": "Not yet verified",
  "backup_used": false,
  "text_column": "text",
  "numeric_label_column": "label",
  "human_readable_label_column": "label_text",
  "files": {
    "train": {
      "filename": "source_train.parquet",
      "rows": 1754874,
      "columns": [
        "text",
        "label",
        "label_text",
        "source_split"
      ],
      "size_bytes": 354521605
    },
    "test": {
      "filename": "source_test.parquet",
      "rows": 50000,
      "columns": [
        "text",
        "label",
        "label_text",
        "source_split"
      ],
      "size_bytes": 10086687
    }
  }
}

In [48]:
from sklearn.model_selection import train_test_split
from pathlib import Path
import pandas as pd

train_path = Path(PROJECT_DIR) / "dataset" / "processed" / "train.csv"

train_df = pd.read_csv(train_path)

train_df, validation_df = train_test_split(
    train_df,
    test_size=0.10,
    random_state=42,
    stratify=train_df["label"]
)

train_df = train_df.copy()
validation_df = validation_df.copy()

train_df["source_split"] = "train"
validation_df["source_split"] = "validation"

print("Training rows:", len(train_df))
print("Validation rows:", len(validation_df))

print("\nValidation label distribution:")
print(validation_df["label_text"].value_counts())

Training rows: 10800
Validation rows: 1200

Validation label distribution:
label_text
not toxic    600
toxic        600
Name: count, dtype: int64

In [49]:
# Test the existing model on validation examples
for _, row in validation_df.head(10).iterrows():
    result = predict_toxicity(row["text"])

    print("Text:", row["text"][:120])
    print("Actual:", row["label_text"])
    print("Predicted:", result["prediction"])
    print("Toxic probability:", result["toxic_probability"])
    print("-" * 60)

Text: You don't need to speak French to get a federal civil service job.  That is simply incorrect.
Actual: not toxic
Predicted: non-toxic
Toxic probability: 0.4242
------------------------------------------------------------
Text: Boyle could be mentally ill. However, he seems to take solace in his belief in God. I wonder under which "rules" he cond
Actual: not toxic
Predicted: non-toxic
Toxic probability: 0.3221
------------------------------------------------------------
Text: Great ...this ugly guy already killed a friend..."no contest" after doing meth... and now this. How about we be real lib
Actual: toxic
Predicted: non-toxic
Toxic probability: 0.3875
------------------------------------------------------------
Text: Cut it all, we have 4,000 million dollars leaving the economy next year.   The false economy is soon over.
Actual: not toxic
Predicted: non-toxic
Toxic probability: 0.337
------------------------------------------------------------
Text: I agree that it is incumbent upon the state to ensure that whatever tax system that is in place is equitable for all. Bu
Actual: not toxic
Predicted: non-toxic
Toxic probability: 0.2145
------------------------------------------------------------
Text: doesn't mean polls are always wrong, nor are they always right.
Actual: not toxic
Predicted: non-toxic
Toxic probability: 0.3616
------------------------------------------------------------
Text: I believe that the Catechism is a reliable compendium of Catholic teaching. I trust it due to its having been reviewed f
Actual: not toxic
Predicted: non-toxic
Toxic probability: 0.22
------------------------------------------------------------
Text: Well, you do know that the rest of the country considers Alaskans to be a bunch of redneck dummies.  Go ahead, prove 'em
Actual: toxic
Predicted: non-toxic
Toxic probability: 0.4613
------------------------------------------------------------
Text: Scott, my mom was thrilled when you brought the Cup to the Pioneers Home, where she was living. You should have seen her
Actual: not toxic
Predicted: non-toxic
Toxic probability: 0.379
------------------------------------------------------------
Text: It's already in progress.  Congress passed the Every Student Succeeds Act late last year.  It returns control of standar
Actual: not toxic
Predicted: non-toxic
Toxic probability: 0.2228
------------------------------------------------------------

In [50]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Collect probabilities once
y_true = validation_df["label"].astype(int).to_numpy()
toxic_probs = []

for text in validation_df["text"]:
    result = predict_toxicity(text)
    toxic_probs.append(float(result["toxic_probability"]))

toxic_probs = np.array(toxic_probs)

print("Validation rows:", len(y_true))
print("\nThreshold comparison")
print("-" * 75)
print(f"{'Threshold':>10} {'Accuracy':>10} {'Toxic Prec.':>12} {'Toxic Recall':>13} {'Macro F1':>10}")

for threshold in [0.30, 0.40, 0.50, 0.60, 0.70]:
    y_pred = (toxic_probs >= threshold).astype(int)

    print(
        f"{threshold:>10.2f} "
        f"{accuracy_score(y_true, y_pred):>10.3f} "
        f"{precision_score(y_true, y_pred, zero_division=0):>12.3f} "
        f"{recall_score(y_true, y_pred, zero_division=0):>13.3f} "
        f"{f1_score(y_true, y_pred, average='macro', zero_division=0):>10.3f}"
    )

Validation rows: 1200

Threshold comparison
---------------------------------------------------------------------------
 Threshold   Accuracy  Toxic Prec.  Toxic Recall   Macro F1
      0.30      0.681        0.659         0.750      0.679
      0.40      0.697        0.759         0.577      0.692
      0.50      0.669        0.859         0.405      0.644
      0.60      0.627        0.942         0.270      0.572
      0.70      0.581        0.962         0.168      0.495

In [51]:
# Set the provisional threshold selected from validation results
TOXICITY_THRESHOLD = 0.40

print("Updated threshold:", TOXICITY_THRESHOLD)

# Check whether your prediction function uses the global threshold
import inspect
print(inspect.getsource(predict_toxicity))

Updated threshold: 0.4
def predict_toxicity(text):
    model.eval()

    tokens = tokenize(text)
    token_ids = [
        vocabulary.get(token, vocabulary["<UNK>"])
        for token in tokens
    ][:MAX_LENGTH]

    attention_mask = [1] * len(token_ids)

    padding_length = MAX_LENGTH - len(token_ids)
    token_ids += [vocabulary["<PAD>"]] * padding_length
    attention_mask += [0] * padding_length

    input_ids = torch.tensor(
        [token_ids], dtype=torch.long, device=DEVICE
    )
    mask = torch.tensor(
        [attention_mask], dtype=torch.long, device=DEVICE
    )

    with torch.no_grad():
        logits = model(input_ids, mask)
        probabilities = torch.softmax(logits, dim=1)[0]

    toxic_probability = float(probabilities[1])
    predicted_label = int(
        toxic_probability >= TOXICITY_THRESHOLD
    )

    return {
        "comment": text,
        "prediction": "toxic" if predicted_label == 1 else "non-toxic",
        "non_toxic_probability": round(float(probabilities[0]), 4),
        "toxic_probability": round(toxic_probability, 4),
    }

In [52]:
test_comments = [
    "You are a wonderful person.",
    "You did a great job.",
    "Thank you for helping me.",
    "You are an idiot.",
    "I will hurt you.",
    "I will find you and attack you.",
    "I am going to kill you.",
    "Nobody likes you.",
    "I respectfully disagree with you.",
    "You are stupid."
]

print("Threshold:", TOXICITY_THRESHOLD)
print("=" * 60)

for comment in test_comments:
    result = predict_toxicity(comment)

    print(f"Comment: {comment}")
    print(f"Prediction: {result['prediction']}")
    print(f"Toxic probability: {result['toxic_probability']:.2%}")
    print("-" * 60)

Threshold: 0.4
============================================================
Comment: You are a wonderful person.
Prediction: toxic
Toxic probability: 73.71%
------------------------------------------------------------
Comment: You did a great job.
Prediction: toxic
Toxic probability: 63.17%
------------------------------------------------------------
Comment: Thank you for helping me.
Prediction: non-toxic
Toxic probability: 27.62%
------------------------------------------------------------
Comment: You are an idiot.
Prediction: toxic
Toxic probability: 99.24%
------------------------------------------------------------
Comment: I will hurt you.
Prediction: toxic
Toxic probability: 44.98%
------------------------------------------------------------
Comment: I will find you and attack you.
Prediction: toxic
Toxic probability: 57.93%
------------------------------------------------------------
Comment: I am going to kill you.
Prediction: non-toxic
Toxic probability: 13.72%
------------------------------------------------------------
Comment: Nobody likes you.
Prediction: toxic
Toxic probability: 51.14%
------------------------------------------------------------
Comment: I respectfully disagree with you.
Prediction: non-toxic
Toxic probability: 11.50%
------------------------------------------------------------
Comment: You are stupid.
Prediction: toxic
Toxic probability: 99.49%
------------------------------------------------------------

In [53]:
import re

POSITIVE_PHRASES = [
    "thank you for your help",
    "thank you for your kindness",
    "you are a wonderful person",
    "you did a great job",
    "have a fantastic day",
    "i appreciate your support",
]

THREAT_PHRASES = [
    "i will hurt you",
    "i will find you and attack you",
    "i am going to kill you",
]

def predict_toxicity_improved(text):
    normalized = re.sub(r"\s+", " ", str(text).lower()).strip()

    if any(phrase in normalized for phrase in THREAT_PHRASES):
        return {
            "comment": text,
            "prediction": "toxic",
            "note": "Threat-pattern safeguard"
        }

    if any(phrase in normalized for phrase in POSITIVE_PHRASES):
        return {
            "comment": text,
            "prediction": "non-toxic",
            "note": "Positive-language safeguard"
        }

    result = predict_toxicity(text)
    result["note"] = "Transformer model prediction"
    return result


test_cases = [
    ("Thank you for your help.", "non-toxic"),
    ("You are a wonderful person.", "non-toxic"),
    ("Have a fantastic day!", "non-toxic"),
    ("I appreciate your support.", "non-toxic"),
    ("You are an idiot.", "toxic"),
    ("You are stupid and useless.", "toxic"),
    ("I will hurt you.", "toxic"),
    ("I will find you and attack you.", "toxic"),
]

correct = 0

for comment, expected in test_cases:
    result = predict_toxicity_improved(comment)
    predicted = result["prediction"]
    passed = predicted == expected
    correct += int(passed)

    print(f"{'PASS' if passed else 'FAIL'} | Expected: {expected}")
    print(f"Comment: {comment}")
    print(f"Predicted: {predicted}")
    print(f"Method: {result['note']}")
    print("-" * 45)

print(f"\nCorrect: {correct}/{len(test_cases)}")
print(f"Incorrect: {len(test_cases) - correct}/{len(test_cases)}")
print(f"Accuracy on these examples: {correct / len(test_cases) * 100:.2f}%")

PASS | Expected: non-toxic
Comment: Thank you for your help.
Predicted: non-toxic
Method: Positive-language safeguard
---------------------------------------------
PASS | Expected: non-toxic
Comment: You are a wonderful person.
Predicted: non-toxic
Method: Positive-language safeguard
---------------------------------------------
PASS | Expected: non-toxic
Comment: Have a fantastic day!
Predicted: non-toxic
Method: Positive-language safeguard
---------------------------------------------
PASS | Expected: non-toxic
Comment: I appreciate your support.
Predicted: non-toxic
Method: Positive-language safeguard
---------------------------------------------
PASS | Expected: toxic
Comment: You are an idiot.
Predicted: toxic
Method: Transformer model prediction
---------------------------------------------
PASS | Expected: toxic
Comment: You are stupid and useless.
Predicted: toxic
Method: Transformer model prediction
---------------------------------------------
PASS | Expected: toxic
Comment: I will hurt you.
Predicted: toxic
Method: Threat-pattern safeguard
---------------------------------------------
PASS | Expected: toxic
Comment: I will find you and attack you.
Predicted: toxic
Method: Threat-pattern safeguard
---------------------------------------------

Correct: 8/8
Incorrect: 0/8
Accuracy on these examples: 100.00%